version: '3.8'

networks:
  sites:
    external: true

services:
  # MinIO S3-compatible object storage
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_CONSOLE_ADDRESS=:9001
      - MINIO_ADDRESS=:9000
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    networks:
      - sites
    restart: unless-stopped
    command: server /data --console-address ":9001"
    labels:
      - "traefik.enable=true"
      # MinIO Console (Web UI)
      - "traefik.http.routers.minio-console.rule=Host(`sites`) && PathPrefix(`/minio`)"
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.http.middlewares.minio-console-stripprefix.stripprefix.prefixes=/minio"
      - "traefik.http.routers.minio-console.middlewares=minio-console-stripprefix"
      # MinIO API endpoint
      - "traefik.http.routers.minio-api.rule=Host(`sites`) && PathPrefix(`/minio-api`)"
      - "traefik.http.routers.minio-api.entrypoints=web"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.minio-api-stripprefix.stripprefix.prefixes=/minio-api"
      - "traefik.http.routers.minio-api.middlewares=minio-api-stripprefix"

  # MinIO Client (mc) for bucket management
  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    networks:
      - sites
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to be ready...';
      until mc alias set local http://minio:9000 minioadmin minioadmin123; do
        echo 'MinIO not ready, waiting...';
        sleep 2;
      done;
      echo 'MinIO is ready!';
      
      echo 'Creating default buckets...';
      mc mb local/datasets --ignore-existing;
      mc mb local/models --ignore-existing;
      mc mb local/artifacts --ignore-existing;
      mc mb local/checkpoints --ignore-existing;
      mc mb local/experiments --ignore-existing;
      
      echo 'Setting bucket policies...';
      mc anonymous set public local/datasets;
      mc anonymous set public local/models;
      
      echo 'MinIO setup complete!';
      tail -f /dev/null;
      "

